// src/lib/components/home/ScrollDown.svelte
<div class="home__scroll">
	<a href="#about" class="home__scroll-button button--flex">
		<svg
			width="32px"
			height="32px"
			class="home__scroll-mouse"
			viewBox="0 0 247 390"
			version="1.1"
			xmlns="http://www.w3.org/2000/svg"
			xmlnsXlink="http://www.w3.org/1999/xlink"
			style={{
				fillRule: 'evenodd',
				clipRule: 'evenodd',
				strokeLinecap: 'round',
				strokeLinejoin: 'round',
				strokeMiterlimit: '1.5'
			}}
		>
			<path
				class="wheel"
				d="M123.359,79.775l0,72.843"
				style={{
					fill: 'none',
					stroke: 'var(--title-color)',
					strokeWidth: '20px'
				}}
			></path>
			<path
				id="mouse"
				d="M236.717,123.359c0,-62.565 -50.794,-113.359 -113.358,-113.359c-62.565,0 -113.359,50.794 -113.359,113.359l0,143.237c0,62.565 50.794,113.359 113.359,113.359c62.564,0 113.358,-50.794 113.358,-113.359l0,-143.237Z"
				style={{
					fill: 'none',
					stroke: 'var(--title-color)',
					strokeWidth: '20px'
				}}
			></path>
		</svg>
		<span class="home__scroll-name">Scroll Down</span>
		<i class="uil uil-arrow-down home__scroll-arrow"></i>
	</a>
</div>

<style>
	.home__scroll {
		margin-left: 9.25rem;
	}

	.wheel {
		animation: scroll 2s ease infinite;
	}

	@keyframes scroll {
		0% {
			transform: translateY(0);
		}

		30% {
			transform: translateY(3.75rem);
		}
	}

	.home__scroll-name {
		color: var(--title-color);
		font-weight: var(--font-medium);
		margin-right: var(--mb-0-25);
		margin-left: 2px;
	}

	.home__scroll-arrow {
		font-size: 1.25rem;
		color: var(--title-color);
	}

	/*=============== BREAKPOINTS ===============*/
	/* For large devices */
	@media screen and (max-width: 992px) {
		.home__scroll {
			margin-left: 7.5rem;
		}
	}

	/* For medium devices */
	@media screen and (max-width: 768px) {
		.home__scroll {
			display: none;
		}
	}
</style>

// src/app/components/scrolldown/ScrollDown.tsx
import styles from './ScrollDown.module.css';
import classNames from 'classnames';
import Link from 'next/link';
import React from 'react';

const ScrollDown = () => {
    return (
        <div className={styles.home__scroll}>
            <Link href="#about" className={classNames('home__scroll-button', 'button--flex')}>
                <svg
                    width="32px"
                    height="32px"
                    className="home__scroll-mouse"
                    viewBox="0 0 247 390"
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    style={{
                        fillRule: 'evenodd',
                        clipRule: 'evenodd',
                        strokeLinecap: 'round',
                        strokeLinejoin: 'round',
                        strokeMiterlimit: '1.5',
                    }}
                >
                    <path
                        className={classNames(styles.wheel)}
                        d="M123.359,79.775l0,72.843"
                        style={{
                            fill: 'none',
                            stroke: 'var(--title-color)',
                            strokeWidth: '20px',
                        }}
                    ></path>
                    <path
                        id="mouse"
                        d="M236.717,123.359c0,-62.565 -50.794,-113.359 -113.358,-113.359c-62.565,0 -113.359,50.794 -113.359,113.359l0,143.237c0,62.565 50.794,113.359 113.359,113.359c62.564,0 113.358,-50.794 113.358,-113.359l0,-143.237Z"
                        style={{
                            fill: 'none',
                            stroke: 'var(--title-color)',
                            strokeWidth: '20px',
                        }}
                    ></path>
                </svg>
                <span className={classNames(styles.home__scrollName)}>Scroll Down</span>
                <i className={classNames('uil', 'uil-arrow-down', styles.home__scrollArrow)}></i>
            </Link>
        </div>
    );
};

export default ScrollDown;
